[package]
name = "slang-reflector"
version = "0.1.0"
edition = "2024"

[dependencies]
shader-slang = { git = "https://github.com/FloatyMonkey/slang-rs"}
serde = { version = "1.0", optional = true }

[features]
derive-serde = ["dep:serde", "shader-slang/serde"]
