[package]
name = "slang-reflector"
version = "0.1.0"
edition = "2024"

[dependencies]
slang = { git = "https://github.com/Devon7925/slang-rs"}
serde = { version = "1.0", optional = true }

[features]
derive-serde = ["dep:serde", "slang/serde"]
